### ISSUE TITLE
Add swarm.fraction.tags property to camel fraction pom.xml files 

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-swarm-archive/wildfly-swarm-camel#54]
According to the Swarm documentation (https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/fraction_authoring.html -  see Root), to make a fraction available within the Project Generator, some properties are required as 

```
<swarm.fraction.tags> 
<swarm.fraction.internal>
```
Such properties are not defined for Camel Swarm. Was that intentional ?

**Comment by jamesnetherton** [comment]
`exposed-components.json` makes the fraction available to the generator. Those tags are additional metadata to categorise the fractions into logical groups. E.g you could search for 'management' and Jolokia would show up in the results.

There's no harm in adding 'swarm.fraction.tags' to to the camel POMs. Just need to think of some suitable tags for each fraction...

**Comment by cmoulliard** [comment]
Can the documentation be updated to include this response please ?

**Comment by tdiesler** [comment]
Moved to: https://issues.jboss.org/browse/SWARM-562
